### ISSUE TITLE
Update dependencies for library and konvert to Kotlin for readability

### ISSUE THREAD

**Issue by LukasAnda** [nisrulz/packagehunter#2]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behaviour?**
As expected, but the code is quite long and can be simplified
**If the current behaviour is a bug, please provide the steps to reproduce.**

**Any logs, error output, bug reports etc?**

**What is the expected behaviour?**

**Any other comments?**

I can create a pull request in few weeks so you can merge it

**What versions of software are you using?**
+ **Device Information:** 

+ **Android Version:** 

+ **Configuration Information:** 

+ **Misc:**

**Comment by nisrulz** [comment]
As an app, it makes sense to convert to Kotlin but as a library, it doesn't. Converting to Kotlin only means that now the library would have a transitive dependency on the Kotlin standard library. For people who have yet to move to Kotlin in their app's the library if added will only add bloat to their app.

On the other hand, this being in Java is completely useable in Kotlin world. However in the future when there are enough users of Kotlin on Android the library could be ported Kotlin. Until then I do not see any benefit in porting this to Kotlin.

Closing as this proposal doesn't bring any useful benefit to users of this library.

**Comment by LukasAnda** [comment]
Okay, no problem. Also, what about updating the dependencies to the latest version ? The support libraries have moved to androidx library

**Comment by nisrulz** [comment]
Packagehunter does not depend on any support library  😄 

Take a look at the dependencies block [here](https://github.com/nisrulz/packagehunter/blob/master/packagehunter/build.gradle#L37-L40)

**Comment by LukasAnda** [comment]
Oh my fault, saw those dependencies for sample app :D
